Tech: rétrograde importlib-metadata pour résoudre un conflit
```
ERROR: Cannot install importlib-metadata==3.1.0, pluggy 0.13.1 and tox 3.20.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested importlib-metadata==3.1.0
    pluggy 0.13.1 depends on importlib-metadata>=0.12; python_version < "3.8"
    tox 3.20.1 depends on importlib-metadata<3 and >=0.12; python_version < "3.8"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```